create table orders
(server varchar2(20),
transactionid varchar2(200),
orderno number,
secid integer,
board varchar2(20),
seccode varchar2(20),
client varchar2(200),
status varchar2(20),
buysell char(1),
time date,
expdate date,
origin_orderno number,
accepttime date,
brokerref varchar2(200),
value number(20,6),
accruedint number,
settlecode varchar2(200),
balance integer,
price number(20,6),
quantity integer,
hidden integer,
yield number,
withdrawtime date,
condition varchar2(200),
conditionvalue number,
validafter date,
validbefore date,
maxcomission number,
result varchar2(200),

bymarket number,
nosplit number,
usecredit number,
unfilled varchar2(20),
cond_type varchar2(50),
cond_value number
);
